steps:
  # 1. Controlla se ci sono modifiche nella cartella server (back-end)
  - name: "gcr.io/cloud-builders/git"
    id: "Check for BE changes"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if git diff --name-only $COMMIT_SHA^ $COMMIT_SHA | grep -q "^server/"; then
          echo "Changes detected in back-end, triggering BE build."
          echo "true" > /workspace/build_backend
        else
          echo "No changes in back-end, skipping BE build."
          echo "false" > /workspace/build_backend
        fi

  # 2. Controlla se ci sono modifiche nella cartella frontend
  - name: "gcr.io/cloud-builders/git"
    id: "Check for FE changes"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if git diff --name-only $COMMIT_SHA^ $COMMIT_SHA | grep -q "^frontend/"; then
          echo "Changes detected in frontend, triggering FE build."
          echo "true" > /workspace/build_frontend
        else
          echo "No changes in frontend, skipping FE build."
          echo "false" > /workspace/build_frontend
        fi

  # 3. Build and deploy BE (back-end)
  - name: "gcr.io/cloud-builders/docker"
    id: "Build BE Docker image"
    if: "substitute('$(cat /workspace/build_backend)', 'true', 'true', 'false', 'false') == 'true'"
    args:
      - "build"
      - "-t"
      - "europe-west1-docker.pkg.dev/test-sere/test-repo/hello-backend:$COMMIT_SHA" # Nominare hello-backend
      - "server/" # Cartella del back-end

  - name: "gcr.io/cloud-builders/docker"
    id: "Push BE Docker image to Artifact Registry"
    if: "substitute('$(cat /workspace/build_backend)', 'true', 'true', 'false', 'false') == 'true'"
    args:
      - "push"
      - "europe-west1-docker.pkg.dev/test-sere/test-repo/hello-backend:$COMMIT_SHA" # Nominare hello-backend

  - name: "gcr.io/cloud-builders/gcloud"
    id: "Deploy BE to Cloud Run"
    if: "substitute('$(cat /workspace/build_backend)', 'true', 'true', 'false', 'false') == 'true'"
    args:
      - "run"
      - "deploy"
      - "hello-backend" # Nominare hello-backend su Cloud Run
      - "--image"
      - "europe-west1-docker.pkg.dev/test-sere/test-repo/hello-backend:$COMMIT_SHA"
      - "--region"
      - "europe-west1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"

  # 4. Build and deploy FE (front-end)
  - name: "gcr.io/cloud-builders/docker"
    id: "Build FE Docker image"
    if: "substitute('$(cat /workspace/build_frontend)', 'true', 'true', 'false', 'false') == 'true'"
    args:
      - "build"
      - "-t"
      - "europe-west1-docker.pkg.dev/test-sere/test-repo/hello-frontend:$COMMIT_SHA" # Nominare hello-frontend
      - "frontend/" # Cartella del front-end

  - name: "gcr.io/cloud-builders/docker"
    id: "Push FE Docker image to Artifact Registry"
    if: "substitute('$(cat /workspace/build_frontend)', 'true', 'true', 'false', 'false') == 'true'"
    args:
      - "push"
      - "europe-west1-docker.pkg.dev/test-sere/test-repo/hello-frontend:$COMMIT_SHA" # Nominare hello-frontend

  - name: "gcr.io/cloud-builders/gcloud"
    id: "Deploy FE to Cloud Run"
    if: "substitute('$(cat /workspace/build_frontend)', 'true', 'true', 'false', 'false') == 'true'"
    args:
      - "run"
      - "deploy"
      - "hello-frontend" # Nominare hello-frontend su Cloud Run
      - "--image"
      - "europe-west1-docker.pkg.dev/test-sere/test-repo/hello-frontend:$COMMIT_SHA"
      - "--region"
      - "europe-west1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"

images:
  - "europe-west1-docker.pkg.dev/test-sere/test-repo/hello-backend:$COMMIT_SHA"
  - "europe-west1-docker.pkg.dev/test-sere/test-repo/hello-frontend:$COMMIT_SHA"
