options:
  logging: CLOUD_LOGGING_ONLY # Registra i log su Cloud Logging

steps:
  # 1. Controlla se ci sono modifiche nella cartella server (back-end)
  - name: "gcr.io/cloud-builders/git"
    id: "Check for BE changes"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        # Fetch latest changes from origin
        git fetch origin
        # Recupera gli ultimi due commit
        COMMIT_SHA=$(git rev-parse HEAD)
        PREVIOUS_COMMIT_SHA=$(git log --pretty=format:"%H" -n 2 | tail -n 1)
        echo "Comparing commits: $PREVIOUS_COMMIT_SHA vs $COMMIT_SHA"
        # Controlla le modifiche nella cartella 'server'
        if git diff --name-only $PREVIOUS_COMMIT_SHA $COMMIT_SHA | grep -q "^server/"; then
          echo "Changes detected in back-end, triggering BE build."
          echo "true" > /workspace/build_backend
        else
          echo "No changes in back-end, skipping BE build."
          echo "false" > /workspace/build_backend
        fi

  # 2. Controlla se ci sono modifiche nella cartella frontend
  - name: "gcr.io/cloud-builders/git"
    id: "Check for FE changes"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        # Fetch latest changes from origin
        git fetch origin
        # Recupera gli ultimi due commit
        COMMIT_SHA=$(git rev-parse HEAD)
        PREVIOUS_COMMIT_SHA=$(git log --pretty=format:"%H" -n 2 | tail -n 1)
        echo "Comparing commits: $PREVIOUS_COMMIT_SHA vs $COMMIT_SHA"
        # Controlla le modifiche nella cartella 'frontend'
        if git diff --name-only $PREVIOUS_COMMIT_SHA $COMMIT_SHA | grep -q "^frontend/"; then
          echo "Changes detected in frontend, triggering FE build."
          echo "true" > /workspace/build_frontend
        else
          echo "No changes in frontend, skipping FE build."
          echo "false" > /workspace/build_frontend
        fi

  # 3. Build and deploy BE (back-end)
  - name: "gcr.io/cloud-builders/docker"
    id: "Build BE Docker image"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [[ $(cat /workspace/build_backend) == "true" ]]; then
          echo "Building Back-End Docker image..."
          docker build -t europe-west1-docker.pkg.dev/test-sere/test-repo/hello-backend:$SHORT_SHA server/
        else
          echo "Skipping Back-End build as no changes detected."
        fi

  - name: "gcr.io/cloud-builders/docker"
    id: "Push BE Docker image to Artifact Registry"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [[ $(cat /workspace/build_backend) == "true" ]]; then
          echo "Pushing Back-End Docker image to Artifact Registry..."
          docker push europe-west1-docker.pkg.dev/test-sere/test-repo/hello-backend:$SHORT_SHA
        else
          echo "Skipping Back-End image push."
        fi

  - name: "gcr.io/cloud-builders/gcloud"
    id: "Deploy BE to Cloud Run"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [[ $(cat /workspace/build_backend) == "true" ]]; then
          echo "Deploying Back-End to Cloud Run..."
          gcloud run deploy hello-backend --image europe-west1-docker.pkg.dev/test-sere/test-repo/hello-backend:$SHORT_SHA --region europe-west1 --platform managed --allow-unauthenticated
        else
          echo "Skipping Back-End deployment."
        fi

  # 4. Build and deploy FE (front-end)
  - name: "gcr.io/cloud-builders/docker"
    id: "Build FE Docker image"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [[ $(cat /workspace/build_frontend) == "true" ]]; then
          echo "Building Front-End Docker image..."
          docker build -t europe-west1-docker.pkg.dev/test-sere/test-repo/hello-frontend:$SHORT_SHA frontend/
        else
          echo "Skipping Front-End build as no changes detected."
        fi

  - name: "gcr.io/cloud-builders/docker"
    id: "Push FE Docker image to Artifact Registry"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [[ $(cat /workspace/build_frontend) == "true" ]]; then
          echo "Pushing Front-End Docker image to Artifact Registry..."
          docker push europe-west1-docker.pkg.dev/test-sere/test-repo/hello-frontend:$SHORT_SHA
        else
          echo "Skipping Front-End image push."
        fi

  - name: "gcr.io/cloud-builders/gcloud"
    id: "Deploy FE to Cloud Run"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [[ $(cat /workspace/build_frontend) == "true" ]]; then
          echo "Deploying Front-End to Cloud Run..."
          gcloud run deploy hello-frontend --image europe-west1-docker.pkg.dev/test-sere/test-repo/hello-frontend:$SHORT_SHA --region europe-west1 --platform managed --allow-unauthenticated
        else
          echo "Skipping Front-End deployment."
        fi
